### ISSUE TITLE
Problems with channels

### ISSUE THREAD

**Issue by Exorcism0666** [Nostalgia-09/AeroChat#13]
If the server doesn't have a category but does have channels, channels on wln won't appear.
![image](https://github.com/Nostalgia-09/AeroChat/assets/46537034/96792979-bdc6-452b-ba28-1251bff9aa83)
![image](https://github.com/Nostalgia-09/AeroChat/assets/46537034/8ca891be-fa14-4857-bf22-d3a2058818c6)

**Comment by not-nullptr** [comment]
should be fixed with the latest update
