### ISSUE TITLE
Is there a command to install the program silently?

### ISSUE THREAD

**Issue by Exorcism0666** [Nostalgia-09/AeroChat#15]
- microsoft/winget-pkgs#132860

**Comment by not-nullptr** [comment]
apologies; will look into a silent switch now

**Comment by not-nullptr** [comment]
@Exorcism0666 `aerochat-x.x.x-xx.x-setup.exe /S --force-run` should do it, though keep in mind that it releases from the prompt immediately so you'll need to wait for it to close in some other way.
