### ISSUE TITLE
The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library KERNEL32.dll.

### ISSUE THREAD

**Issue by loogi-rgb** [Nostalgia-09/AeroChat#16]
![image](https://github.com/Nostalgia-09/AeroChat/assets/66547175/28037edb-b0bd-49d9-8ce6-d3debe1ec31e)
this could be an issue on my end, think i might've fucked up my pc a little
![image](https://github.com/Nostalgia-09/AeroChat/assets/66547175/6ef3e792-d4e6-4ab7-add0-a6c7b30a8451)

**Comment by StupidGameridk** [comment]
I don't think it runs on Windows 7 because it's an electron app, what Discord runs on, don't know if Windows 7 has certain features for that and I think that's why it's erroring out, I could be wrong though. I get the same thing when I try to run it on Windows 7, so it's not just you

**Comment by StupidGameridk** [comment]
Just looked, they have a patch for Windows 7 now in the new update, just look in the installer
