### ISSUE TITLE
Needing a macOS Release

### ISSUE THREAD

**Issue by theanthonydavenport** [Nostalgia-09/AeroChat#18]
This is a wonderful project, with one slight problem, the client doesn't have a macOS release.

**Comment by theanthonydavenport** [comment]
I have no idea how to compile Github stuff, or Python.

**Comment by not-nullptr** [comment]
> I have no idea how to compile Github stuff, or Python.

i would love to do it but i don't have a mac. there is a fundraiser on my throne for an older mac if you wish to contribute ^-^ https://throne.com/nullptr/item/df158bf7-4d0b-4ef0-b3a4-36118ecc6097

**Comment by theanthonydavenport** [comment]
You can TeamViewer it on my Mac if you like, I wouldn't mind, and I would love it.

**Comment by not-nullptr** [comment]
> You can TeamViewer it on my Mac if you like, I wouldn't mind, and I would love it.

i'd rather not in the case that i'd see personal info or accidentally break the system. thanks for the offer though !

**Comment by theanthonydavenport** [comment]
You won't see personal info, I've made sure of it.
Also, the system is fully backed up and a spare Mac.
