### ISSUE TITLE
Right click menu (context menu) doesn't close on Manjaro Linux

### ISSUE THREAD

**Issue by borealsoul** [Nostalgia-09/AeroChat#21]
After opening any type of context menu, it never closes until I close the whole app. It also stays on top of everything in my desktop. 

I'm using Manjaro Linux with KDE and version `1.0.1-rc.6`

Here's an example, even if I move the windows, the context menu stays on top.
![image](https://github.com/Nostalgia-09/AeroChat/assets/95144965/4fec7cc6-3f13-42c9-a319-bd434b99cbcc)

**Comment by not-nullptr** [comment]
unfortunately linux is entirely unsupported by me; however this is an issue on windows too so i'll look into it

**Comment by borealsoul** [comment]
no problem! just wanted to give a heads-up about this.
