### ISSUE TITLE
Risk of ban ?

### ISSUE THREAD

**Issue by Eevee-Gaming** [Nostalgia-09/AeroChat#24]
Hey, i'm here to ask if AeroChat can ban your Discord account?

Since it's a custom Discord client, Discord might not like this so yeah.

Ripcord (another custom client) banned one of my older accounts, so I wonder if yours could look suspect beyond Discord API.

**Comment by not-nullptr** [comment]
aerochat is not a native app, which means it uses the exact same native code to send http request, which makes ban risk lower than using ripcord. that being said, no guarantees, and you may get banned.
