### ISSUE TITLE
can't see what i'm typing

### ISSUE THREAD

**Issue by s626ch** [Nostalgia-09/AeroChat#9]
this is likely due to my custom windows theme being a dark theme.
would be nice if the text box had a set text color
![Windows_Live_Messenger_THAFbz4uU5](https://github.com/Nostalgia-09/AeroChat/assets/22896890/c67e442b-7bb2-4785-8fee-42f7c5ab1619)

**Comment by s626ch** [comment]
yknow what hold on i'm going to smack this fix into a fork

**Comment by not-nullptr** [comment]
closed in #10
